language: python
python:
  - '3.6'
before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get -y install vlc vlc-plugin-*
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: test
      script:
        - cd tests
        - python test.py
        - cd ..
    - stage: build
      script: 
        - cd src
        - travis_wait python run.py
    - stage: deploy
      script: 
        - cd src
        - bash deploy.sh
env:
  global:
    secure: FCD2Icrv5Q81M17prhQoCQYtLeyIMPGMuL/flLn+TQzpJvqXWBG6yacAhAba93AGErs6r9dZlzvMq/uGi6rgMrA6kKGwUA/lG9f0cWDMS4m+wkULv+W8GTdWvZSgQnZxsde+7P5PorRMi9gtmNuETm0czGuQAMN5KOT9rAF7UD2NSQdpKfoJH/5CCQ+KBMOX5PQetbkx7HwmgF8BC7U0oTnD8QO0ImVWoRs4UNMneytBJVLo5DrCGXl7zsnbgNCDfTtDbtjtJje7wcFUzmBR69uhAgGSSn9ZZ3X5Z1AmiKN5oLIA3dAPAeyWE3X+CY3qu/Kly1NX+huZtEW9WHeQ1LmWNJFgL+sZnPd4x72XlSK6XZv560xAnB5iBr8+0amGat6cw4KOQ58QM4fK5IOPBJ3RRT7bhZp266OayjBHux3FJrmJUzZWRdt0lJhpobIUJqBAiwL43zwEWNkgWywJc3Bl2zH3fCe89e8HzyJrVG9n1k2bnVTi3ovri6xUyRvETCRFmagS+2ul10tyZ6/G694IIGNdoKi9SzAhUWZEBflLGcpR5Cc9Q+8/0lCmhBvwMsmdAg8xSOf6UuP0bLMfFLBHIIdea1Oy+zs9PQAPBr3q1NRTmoLewv8y2OFQMopZAM73/nue7j+yAcAOiWIzreaNoMyJp7mnJ4F8LcjRtqo=
notifications:
  email: false